### ISSUE TITLE
Missing Instruction

### ISSUE THREAD

**Issue by berkserbet** [zacheberhart/Soundcloud-Scraper#1]
Hi Zach, thanks for making this. I want to try it out but I can't seem to find any instructions. Would you be able to add some?

**Comment by wnikola** [comment]
Hi @berkserbet :slightly_smiling_face: 

I know this is kinda old, but I was wondering whether you've managed to run the scraper? Even with the instruction in the README I'm not sure how to create a database, make a seed list, or what file to run next. Also I haven't worked with python before so I'm wondering whether there's a way to install all the required packages at once?

Thanks in advance!

**Comment by berkserbet** [comment]
Unfortunately not, sorry!
